- hosts: targets
  vars:
    - username: root
  tasks:
    - name: mkdir .ssh
      file:
        path=.ssh
        state=directory
        owner={{username}}
        group={{username}}
        mode=0700
    - name: check "already generated ssh-key"
      stat: path=.ssh/id_rsa.pub
      register: fm
    - name: generate ssh key
      shell: ssh-keygen -t rsa -b 4096 -f /{{username}}/.ssh/id_rsa -q -N ""
      when: not fm.stat.exists
    - name: mkdir cytrone
      file:
        path=cytrone/
        state=directory
        owner={{username}}
        group={{username}}
        mode=0755
    - name: mkdir cytrone/images
      file:
        path=cytrone/images
        state=directory
        owner={{username}}
        group={{username}}
        mode=0755
    - name: download base image
      get_url:
        url=https://github.com/crond-jaist/cyris/releases/download/1.0/basevm.tgz
        sha256sum=1c94d9350fd11dd18d421110fb305639f2ccbbd45fe78294d02ffe5f94ad4e71
        dest=cytrone/images/basevm.tgz
    - name: extract base image from download file
      command: tar xf cytrone/images/basevm.tgz
    - name: check "already cloned cyris"
      stat: path=cytrone/cyris
      register: fm
    - name: git clone cyris
      when: not fm.stat.exists
      git:
        repo: "https://github.com/crond-jaist/cyris.git"
        dest: cytrone/cyris
        version: master
